### ISSUE TITLE
fallen is invalid using RoboCupGameControlReturnData constructor

### ISSUE THREAD

**Issue by ijnek** [RoboCup-SPL/GameController#46]
[RoboCupGameControlReturnData's constructor](https://github.com/RoboCup-SPL/GameController/blob/071180739c580bdef51c0bdc393e974881bd8fdb/include/RoboCupGameControlData.h#L138) in ``include/RoboCupGameControlData.h`` sets ``fallen`` to ``255``.

The value ``255`` is explained in SPLStandardMessage, where it was taken from, but not described in RoboCupGameControlData.h. From ``SPLStandardMessage.h``,

> fallen(255), // placeholder to detect in the TCM if this field is not set

Using this constructor, the Robot doesn't show up in the GameController because ``fallenValid = fallenState == 0 || fallenState == 1`` evaluates as ``false`` in [GameControlReturnData.java Line120](https://github.com/RoboCup-SPL/GameController/blob/071180739c580bdef51c0bdc393e974881bd8fdb/src/data/GameControlReturnData.java#L120).

Is this by design or a bug? It took me a while to figure out that the udp connection wasn't the issue. My suggestion would be to have ``fallenValid = fallenState == 0 || fallenState == 1 || fallenState == 255`` instead.

**Comment by ahasselbring** [comment]
It is deliberate that the initial value is invalid in order to force teams to fill the field (which is also the case for `playerNum` and `teamNum`, though I admit that it might be inconsistent to fill `pose`, `ballAge` and `ball` with valid values).

I think initially I was unsure which of the new fields in `RoboCupGameControlReturnData` the GameController should check at all (since they are actually meant for the TCM), but then I decided it would be better not to accept invalid packets so that one would immediately notice something is wrong. I have to change the receiver code anyway because the GameController must relay the messages to the TCM (unicast packets cannot be delivered to multiple programs even with `REUSEADDR`). 

Rather than accepting 255 as valid value, I would revert to checking only the header, player number and team number in https://github.com/RoboCup-SPL/GameController/blob/f846acd6b318f062d140d1515bc4b6d191c84203/src/controller/net/GameControlReturnDataReceiverGC.java#L28

**Comment by ijnek** [comment]
Sounds good, could we add a one-off warning log per robot in the GameController if it decides to throw away a message due to the checks? Just some sort of indication that it's actively throwing away those messages would be helpful.

eg.
```sh
Ignoring packet from 10.0.18.3 due to invalid playerNum: 10
```

**Comment by ahasselbring** [comment]
Since I consider this GameController to be EOL, I don't see a point in adding a warning that it hasn't need for the past 10 years (unless I come across this when implementing forwarding the messages to the TCM).

**Comment by ijnek** [comment]
Sounds good, thanks @ahasselbring
